#!/usr/bin/env bash

BF="\033[1m"
CC="\033[0m"
PW=$(shuf -zer -n8 {A..Z} {a..z} {0..9} | tr -d '\0')

printf "Random Generated VNC Password: ${BF}${PW}${CC}\n"

[ ! -d ${HOME}/.vnc ] && mkdir -p ${HOME}/.vnc
echo ${PW} | /usr/bin/tigervncpasswd -f > ${HOME}/.vnc/passwd

chmod 600 ${HOME}/.vnc/passwd

# NOTE: workaroundk to replace the passwd, since we cannot assign the path of PasswordFile in new tigervncserver
for dir in $(find /tmp -maxdepth 1 -type d -name 'tigervnc.*' -user "$USER"); do
    if [ -f "$dir/passwd" ]; then
        cp "$HOME/.vnc/passwd" "$dir/passwd"
        # echo "Replace the passwd of $dir"
    else
        echo "No passwd file found in $dir"
    fi
done
